log    =    log/$(Cluster)_$(file).log
error  =  error/$(Cluster)_$(file).err
output = output/$(Cluster)_$(file).out

universe = vanilla
executable = ./process_file.sh
arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = process_file.sh,$(file)
transfer_output_files = .

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue file from filelist

